version: '4'

services:
  mongo:
    image: mongo:8.0.3
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin@123
      MONGO_INITDB_DATABASE: OrderDB
    ports:
        - "1103:27017"
    volumes:
        - ./docker-metadata/mongodb_data:/data/db