server:
  port: 8082

spring:
  application:
    name: Book-Service


  datasource:
    url: jdbc:mysql://localhost:1100/BooksDB
    username: admin
    password: admin@123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
        hibernate:
          format_sql: true