server:
  port: 8081

spring:
  application:
    name: User-Service

  datasource:
    url: jdbc:postgresql://localhost:1101/USER-DB
    username: admin
    password: admin@123

  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    hibernate:
          ddl-auto: update





