version: '4'

services:
  postgres_db:
    image: postgres:17.0
    container_name: PostgresContainer
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin@123
      - POSTGRES_DB=USER-DB
    ports:
      - '1101:5432'
    volumes:
      - ./docker-metadata/postgres:/var/lib/postgresql/data