version: '4'

services:
  MySqlDB:
    image: mysql:9.1.0
    container_name: MySqlDB
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root@123
      MYSQL_DATABASE: BooksDB
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin@123
    ports:
      - "1100:3306"
    volumes:
        - ./docker-metadata/mysql:/var/lib/mysql


